path: C:\Users\u11886\Documents\PDI_teste\PDI_teste\data

train: C:\Users\u11886\Documents\PDI_teste\PDI_teste\data\images\train
val: C:\Users\u11886\Documents\PDI_teste\PDI_teste\data\images\val

kpt_shape: [21, 2]
flip_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

names:
  0: hand